### ISSUE TITLE
Module did not self-register since nodejs 0.12

### ISSUE THREAD

**Issue by ericrange** [mscdex/cap#21]
```
module.js:339
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (C:\Users\Eric Range\Documents\GitHub\xyz\node_modules\cap\lib\Cap.
js:3:13)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
```

**Comment by mscdex** [comment]
What version of this module are you using?

**Comment by ericrange** [comment]
latest. 0.0.12

**Comment by ericrange** [comment]
it seems to be a common problem with nodejs 0.12 that this message appear

**Comment by ericrange** [comment]
also with other npm packages

**Comment by crawfordcomeaux** [comment]
I just encountered this. Here's the fix:

```
rm -rf ./node_modules
npm install
```

**Comment by mscdex** [comment]
Yes, with io.js 1.0 and node 0.12, you have to recompile your addons because the ABI changed.
