### ISSUE TITLE
nodeJS v0.12 issue ? 

### ISSUE THREAD

**Issue by gthgame** [mscdex/cap#29]
I can't get the module working with nodeJS v0.12 , only works on 0.10 ?

**Comment by mscdex** [comment]
Can you elaborate on that? Do you get any errors during install? If so, can you post them? Or is there some other problem?

`cap` uses `nan` for compatibility between node/io.js versions, so there shouldn't be any node v0.12 compatibility issues.

**Comment by antoniwan** [comment]
Hi - 

I'm running npm install cap on node -v 0.12.7 and receive the following error

```
npm ERR! cap@0.0.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cap@0.0.15 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cap
npm ERR! There is likely additional logging output above.

```

**Comment by mscdex** [comment]
@antoniwan Can you include the entire log output?

**Comment by Pietro-Vis** [comment]
Same issue with iojs v3.1.0.
Here is the log output
```
$ npm install cap
\
> cap@0.0.15 install /home/pietro/Documenti/projects/pcap/node_modules/cap
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v3.1.0/node-v3.1.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 3.16.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pietro/Documenti/projects/pcap/node_modules/cap
gyp ERR! node -v v3.1.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.0-46-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "cap"
npm ERR! node v3.1.0
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE

npm ERR! cap@0.0.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cap@0.0.15 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pietro/Documenti/projects/pcap/npm-debug.log

```

**Comment by mscdex** [comment]
@Pietro-Vis It looks like you may have installed a vanilla version of npm after installing io.js since it's looking for the wrong URL. io.js bundles a custom patched version of npm/node-gyp so that it looks for a different URL.

**Comment by Pietro-Vis** [comment]
@mscdex Solved by removing npm and iojs and installing the last version of nodejs.

**Comment by mscdex** [comment]
Any 0.12 issues should be resolved in master now.
