### ISSUE TITLE
Error on tests

### ISSUE THREAD

**Issue by layane** [mscdex/cap#37]
When i executed your tests or your exampled i get this error. And the build in https://ci.appveyor.com/project/mscdex/cap fail too

TypeError: device must be a string
    at TypeError (native)
    at Object.<anonymous> (D:\Mis Cosas\Sistema\perfil\Escritorio\sniff\main.js:
11:18)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

i use windows and the last winpcap installed today and use nodejs v5.3.0

thanks!!  very usefull lib

**Comment by layane** [comment]
Solved. findDevice not found my device.

**Comment by mscdex** [comment]
Yeah it looks like AppVeyor switched cloud providers recently and that has affected things on the VM the tests are running on. I'll see what I can do about that.
