### ISSUE TITLE
Cannot open include file: 'nan.h': No such file or directory

### ISSUE THREAD

**Issue by theunreal** [mscdex/cap#52]
Trying to npm install cap on windows 10, gets the following error:

```
c:\xampp\htdocs\node-project>npm install cap --save

> cap@0.1.2 install c:\xampp\htdocs\node-project\node_modules\cap
> node-gyp rebuild


c:\xampp\htdocs\node-project\node_modules\cap>if not defined npm_config_node_gyp (node "C:\Users\home\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" reb
uild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(3): fatal error C1083: Cannot open include file: 'nan.h': No such file or directory [c:\xampp\htdocs\node-project\node_modules\cap\build\cap.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\home\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\home\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\xampp\htdocs\node-project\node_modules\cap
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\home\AppData\Roaming\npm-cache\_logs\2017-08-12T16_32_07_401Z-debug.log

```

Any idea what could have gone wrong?

**Comment by mscdex** [comment]
No idea. Somehow `nan` (a dependency) did not get automatically installed along with `cap`.
