### ISSUE TITLE
Win 10 install error

### ISSUE THREAD

**Issue by fragsalat** [mscdex/cap#56]
Hey there. Is this still maintained somehow?

I tried to install the package with npm i cap.
I installed already wireshark and winpcap.

I'm getting following error
```
D:\Data\projects\ff14-trading-tracker>npm i cap

> cap@0.1.2 install D:\Data\projects\ff14-trading-tracker\node_modules\cap
> node-gyp rebuild


D:\Data\projects\ff14-trading-tracker\node_modules\cap>if not defined npm_config_node_gyp (node "D:\Programme\Entwicklung\NodeJS\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Programme\Entwicklung\NodeJS\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(52): error C2666: 'inet_ntop': 2 overloads have similar conversions [D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj]
  d:\data\projects\ff14-trading-tracker\node_modules\cap\src\windows_polyfills.h(116): note: could be 'char *inet_ntop(int,const void *,char *,socklen_t)' (compiling source file ..\src\binding.cc)
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\ws2tcpip.h(576): note: or       'PCSTR inet_ntop(INT,PVOID,PSTR,std::size_t)' (compiling source file ..\src\binding.cc)
  ..\src\binding.cc(52): note: while trying to match the argument list '(ADDRESS_FAMILY, char *, char [66], socklen_t)'
..\src\binding.cc(584): error C2666: 'inet_ntop': 2 overloads have similar conversions [D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj]
  d:\data\projects\ff14-trading-tracker\node_modules\cap\src\windows_polyfills.h(116): note: could be 'char *inet_ntop(int,const void *,char *,socklen_t)' (compiling source file ..\src\binding.cc)
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\ws2tcpip.h(576): note: or       'PCSTR inet_ntop(INT,PVOID,PSTR,std::size_t)' (compiling source file ..\src\binding.cc)
  ..\src\binding.cc(584): note: while trying to match the argument list '(int, char *, char [22], int)'
..\src\binding.cc(592): error C2666: 'inet_ntop': 2 overloads have similar conversions [D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj]
  d:\data\projects\ff14-trading-tracker\node_modules\cap\src\windows_polyfills.h(116): note: could be 'char *inet_ntop(int,const void *,char *,socklen_t)' (compiling source file ..\src\binding.cc)
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\ws2tcpip.h(576): note: or       'PCSTR inet_ntop(INT,PVOID,PSTR,std::size_t)' (compiling source file ..\src\binding.cc)
  ..\src\binding.cc(592): note: while trying to match the argument list '(int, char *, char [65], int)'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Programme\Entwicklung\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\Programme\\Entwicklung\\NodeJS\\node.exe" "D:\\Programme\\Entwicklung\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Data\projects\ff14-trading-tracker\node_modules\cap
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Do you have a idea why this happens?

**Comment by mscdex** [comment]
What is your build environment?

**Comment by fragsalat** [comment]
Wow that was fast^^
It's win 10. PS I cloned the repository and run node-gyp rebuild and it worked fine. But installing as dependency still doesn't work

**Comment by mscdex** [comment]
What I mean is, what compiler version, etc. are you using?

**Comment by fragsalat** [comment]
Good question. I can not see which compiler is used from the log but I found something like 'msvs_version=2015',

Here is the verbose output
```
npm info it worked if it ends with ok
npm verb cli [ 'D:\\Programme\\Entwicklung\\NodeJS\\node.exe',
npm verb cli   'D:\\Programme\\Entwicklung\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   '--verbose',
npm verb cli   'cap' ]
npm info using npm@5.6.0
npm info using node@v9.5.0
npm verb npm-session 6c525abb93ba302f
npm http fetch GET 304 https://registry.npmjs.org/cap 309ms (from cache)
npm verb correctMkdir C:\Users\tschl\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\tschl\AppData\Roaming\npm-cache\_locks\staging-487b571a47b29ef8.lock for D:\Data\projects\ff14-trading-tracker\node_modules\.staging
npm info lifecycle cap@0.1.2~preinstall: cap@0.1.2
npm info linkStuff cap@0.1.2
npm verb linkBins cap@0.1.2
npm verb linkMans cap@0.1.2
npm info lifecycle cap@0.1.2~install: cap@0.1.2

> cap@0.1.2 install D:\Data\projects\ff14-trading-tracker\node_modules\cap
> node-gyp rebuild


D:\Data\projects\ff14-trading-tracker\node_modules\cap>if not defined npm_config_node_gyp (node "D:\Programme\Entwicklung\NodeJS\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Programme\Entwicklung\NodeJS\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\Programme\\Entwicklung\\NodeJS\\node.exe',
gyp verb cli   'D:\\Programme\\Entwicklung\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\tschl\.windows-build-tools\python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\tschl\.windows-build-tools\python27\python.exe C:\Users\tschl\.windows-build-tools\python27\python.exe
gyp verb check python version `C:\Users\tschl\.windows-build-tools\python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.5.0
gyp verb command install [ '9.5.0' ]
gyp verb install input version string "9.5.0"
gyp verb install installing version: 9.5.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.5.0
gyp verb build dir attempting to create "build" dir: D:\Data\projects\ff14-trading-tracker\node_modules\cap\build
gyp verb build dir "build" dir needed to be created? D:\Data\projects\ff14-trading-tracker\node_modules\cap\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\Data\projects\ff14-trading-tracker\node_modules\cap\config.gypi
gyp verb common.gypi checking for gypi file: D:\Data\projects\ff14-trading-tracker\node_modules\cap\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\tschl\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'D:\\Programme\\Entwicklung\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Data\\projects\\ff14-trading-tracker\\node_modules\\cap\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Programme\\Entwicklung\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\tschl\\.node-gyp\\9.5.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\tschl\\.node-gyp\\9.5.0',
gyp info spawn args   '-Dnode_gyp_dir=D:\\Programme\\Entwicklung\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\tschl\\.node-gyp\\9.5.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Data\\projects\\ff14-trading-tracker\\node_modules\\cap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Data\\projects\\ff14-trading-tracker\\node_modules\\cap\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\tschl\.node-gyp\9.5.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
Der Buildvorgang wurde am 19.02.2018 20:56:29 gestartet.
Projekt "D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\binding.sln" auf Knoten "1" (Standardziele).
ValidateSolutionConfiguration:
  Die Projektmappenkonfiguration "Release|x64" wird erstellt.
Das Projekt "D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\binding.sln" (1) erstellt "D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj" (2) auf Knoten "1" (Standardziele).
PrepareForBuild:
  Das Verzeichnis "Release\obj\cap\" wird erstellt.
  Das Verzeichnis "Release\obj\cap\cap.tlog\" wird erstellt.
InitializeBuildStatus:
  "Release\obj\cap\cap.tlog\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /I"C:\Users\tschl\.node-gyp\9.5.0\include\node" /I"C:\Users\tschl\.node-gyp\9.5.0\src" /I"C:\Users\tschl\.node-gyp\9.5.0\deps\uv\include" /I"C:\Users\tschl\.node-gyp\9.5.0\deps\v8\include" /I..\..\nan /I
  ..\deps\winpcap\Include /Zi /nologo /W3 /WX- /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAME=cap /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D WPCAP /D BUILDING_N
  ODE_EXTENSION /D _WINDLL /GF /Gm- /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\cap\\" /Fd"Release\obj\cap\vc140.pdb" /Gd /TP /wd4267 /wd4351 /wd4355 /wd4800 /wd4251 /errorReport:queue /MP ..\src\binding.cc "D:\Programme\Entwicklung\NodeJS\nod
  e_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc"
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(52): error C2666: 'inet_ntop': 2 overloads have similar conversions [D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj]
  d:\data\projects\ff14-trading-tracker\node_modules\cap\src\windows_polyfills.h(116): note: could be 'char *inet_ntop(int,const void *,char *,socklen_t)' (compiling source file ..\src\binding.cc)
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\ws2tcpip.h(576): note: or       'PCSTR inet_ntop(INT,PVOID,PSTR,std::size_t)' (compiling source file ..\src\binding.cc)
  ..\src\binding.cc(52): note: while trying to match the argument list '(ADDRESS_FAMILY, char *, char [66], socklen_t)'
..\src\binding.cc(584): error C2666: 'inet_ntop': 2 overloads have similar conversions [D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj]
  d:\data\projects\ff14-trading-tracker\node_modules\cap\src\windows_polyfills.h(116): note: could be 'char *inet_ntop(int,const void *,char *,socklen_t)' (compiling source file ..\src\binding.cc)
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\ws2tcpip.h(576): note: or       'PCSTR inet_ntop(INT,PVOID,PSTR,std::size_t)' (compiling source file ..\src\binding.cc)
  ..\src\binding.cc(584): note: while trying to match the argument list '(int, char *, char [22], int)'
..\src\binding.cc(592): error C2666: 'inet_ntop': 2 overloads have similar conversions [D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj]
  d:\data\projects\ff14-trading-tracker\node_modules\cap\src\windows_polyfills.h(116): note: could be 'char *inet_ntop(int,const void *,char *,socklen_t)' (compiling source file ..\src\binding.cc)
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\ws2tcpip.h(576): note: or       'PCSTR inet_ntop(INT,PVOID,PSTR,std::size_t)' (compiling source file ..\src\binding.cc)
  ..\src\binding.cc(592): note: while trying to match the argument list '(int, char *, char [65], int)'
Die Erstellung des Projekts "D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj" ist abgeschlossen (Standardziele) -- FEHLER.

Die Erstellung des Projekts "D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\binding.sln" ist abgeschlossen (Standardziele) -- FEHLER.


Fehler beim Buildvorgang.

"D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\binding.sln" (Standardziel) (1) ->
"D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj" (Standardziel) (2) ->
(ClCompile Ziel) ->
  ..\src\binding.cc(52): error C2666: 'inet_ntop': 2 overloads have similar conversions [D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj]
  ..\src\binding.cc(584): error C2666: 'inet_ntop': 2 overloads have similar conversions [D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj]
  ..\src\binding.cc(592): error C2666: 'inet_ntop': 2 overloads have similar conversions [D:\Data\projects\ff14-trading-tracker\node_modules\cap\build\cap.vcxproj]

    0 Warnung(en)
    3 Fehler

Verstrichene Zeit 00:00:01.95
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Programme\Entwicklung\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\Programme\\Entwicklung\\NodeJS\\node.exe" "D:\\Programme\\Entwicklung\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Data\projects\ff14-trading-tracker\node_modules\cap
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm verb lifecycle cap@0.1.2~install: unsafe-perm in lifecycle true
npm verb lifecycle cap@0.1.2~install: PATH: D:\Programme\Entwicklung\NodeJS\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Data\projects\ff14-trading-tracker\node_modules\cap\node_modules\.bin;D:\Data\projects\ff14-trading-tracker\node_modules\.bin;D:\Programme\Entwicklung\Python\2\;D:\Programme\Entwicklung\Python\2\Scripts;D:\Programme\Entwicklung\Python\Scripts\;D:\Programme\Entwicklung\Python\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Programme\Entwicklung\Git\cmd;D:\Programme\Entwicklung\NodeJS\;C:\Users\tschl\AppData\Local\Microsoft\WindowsApps;D:\Programme\SysGCC\bin;D:\Programme\Entwicklung\Microsoft VS Code\bin;C:\Users\tschl\AppData\Roaming\npm
npm verb lifecycle cap@0.1.2~install: CWD: D:\Data\projects\ff14-trading-tracker\node_modules\cap
npm info lifecycle cap@0.1.2~install: Failed to exec install script
npm verb unlock done using C:\Users\tschl\AppData\Roaming\npm-cache\_locks\staging-487b571a47b29ef8.lock for D:\Data\projects\ff14-trading-tracker\node_modules\.staging
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: cap@0.1.2 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (D:\Programme\Entwicklung\NodeJS\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
npm verb stack     at EventEmitter.emit (events.js:160:13)
npm verb stack     at ChildProcess.<anonymous> (D:\Programme\Entwicklung\NodeJS\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:160:13)
npm verb stack     at maybeClose (internal/child_process.js:943:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm verb pkgid cap@0.1.2
npm verb cwd D:\Data\projects\ff14-trading-tracker
npm verb Windows_NT 10.0.16299
npm verb argv "D:\\Programme\\Entwicklung\\NodeJS\\node.exe" "D:\\Programme\\Entwicklung\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "i" "--verbose" "cap"
npm verb node v9.5.0
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
```

**Comment by fragsalat** [comment]
So I re-installed build tools and got the error that winsock2.h is missing. Then I re-installed windows sdk and get the same error as before -,-

**Comment by mscdex** [comment]
Can you try the master branch now? `npm install https://github.com/mscdex/cap/tarball/master`

I think the issue should be resolved...

**Comment by fragsalat** [comment]
It's working now.
You are my hero today <3

Thank you very much for this awesome and super fast support.
