### ISSUE TITLE
npm install cap error

### ISSUE THREAD

**Issue by Lafko** [mscdex/cap#66]
```
C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64>npm --verbose install cap
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Users\\Bylaf\\Desktop\\node-v10.0.0-win-x64\\node.exe',
npm verb cli   'C:\\Users\\Bylaf\\Desktop\\node-v10.0.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose',
npm verb cli   'install',
npm verb cli   'cap' ]
npm info using npm@5.6.0
npm info using node@v10.0.0
npm verb npm-session b8ab96d5652d1607
npm http fetch GET 304 https://registry.npmjs.org/cap 324ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 101ms (from cache)
npm verb correctMkdir C:\Users\Bylaf\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\Bylaf\AppData\Roaming\npm-cache\_locks\staging-6bc8cab54f91a25b.lock for C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\.staging
npm info lifecycle nan@2.10.0~preinstall: nan@2.10.0
npm info lifecycle cap@0.2.0~preinstall: cap@0.2.0
npm info linkStuff nan@2.10.0
npm verb linkBins nan@2.10.0
npm verb linkMans nan@2.10.0
npm info linkStuff cap@0.2.0
npm verb linkBins cap@0.2.0
npm verb linkMans cap@0.2.0
npm info lifecycle nan@2.10.0~install: nan@2.10.0
npm info lifecycle cap@0.2.0~install: cap@0.2.0

> cap@0.2.0 install C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\cap
> node-gyp rebuild


C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\cap>if not defined npm_config_node_gyp (node "C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
"node" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
npm verb lifecycle cap@0.2.0~install: unsafe-perm in lifecycle true
npm verb lifecycle cap@0.2.0~install: PATH: C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\cap\node_modules\.bin;C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Boxstarter;C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36-32\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Livestreamer;C:\Program Files\010 Editor;C:\apache-maven-3.5.3\bin;C:\Program Files\dotnet\;C:\apache-maven-3.5.3\bin;C:\Users\Bylaf\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Bylaf\AppData\Local\Programs\Python\Python36-32\;C:\Users\Bylaf\AppData\Local\Microsoft\WindowsApps;C:\Users\Bylaf\AppData\Local\GitHubDesktop\binC:\Program Files\Java\jdk1.8.0_161\bin;C:\ProgramData\chocolatey\bin;C:\Users\Bylaf\AppData\Local\GitHubDesktop\bin
npm verb lifecycle cap@0.2.0~install: CWD: C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\cap
npm info lifecycle cap@0.2.0~install: Failed to exec install script
npm verb unlock done using C:\Users\Bylaf\AppData\Roaming\npm-cache\_locks\staging-6bc8cab54f91a25b.lock for C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\.staging
npm verb stack Error: cap@0.2.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
npm verb stack     at EventEmitter.emit (events.js:182:13)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:947:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
npm verb pkgid cap@0.2.0
npm verb cwd C:\Users\Bylaf\Desktop\node-v10.0.0-win-x64
npm verb Windows_NT 10.0.16299
npm verb argv "C:\\Users\\Bylaf\\Desktop\\node-v10.0.0-win-x64\\node.exe" "C:\\Users\\Bylaf\\Desktop\\node-v10.0.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "--verbose" "install" "cap"
npm verb node v10.0.0
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bylaf\AppData\Roaming\npm-cache\_logs\2018-05-01T21_05_52_545Z-debug.log
```

**Comment by mscdex** [comment]
You might need to actually have node installed (not just extracted to a directory) to be able to use npm correctly? I am not sure. Either way, the problem is outside of this addon. I would suggest start asking on the [node-gyp issue tracker](https://github.com/nodejs/node-gyp/issues) and/or [npm issue tracker](https://github.com/npm/npm/issues) instead.

**Comment by Lafko** [comment]
> cap@0.2.0 install C:\Windows\system32\node_modules\cap
> node-gyp rebuild


C:\Windows\system32\node_modules\cap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
MSBUILD : error MSB1009: файл проекта не существует.
Ключ: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\cap
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cap@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cap@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bylaf\AppData\Roaming\npm-cache\_logs\2018-05-01T22_34_23_292Z-debug.log

**Comment by Lafko** [comment]
nvm help node 9+
