### ISSUE TITLE
Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by npdev453** [mscdex/cap#7]
```
D:\nodep\work>node server

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: %1 is not a valid Win32 application.
D:\nodep\node_modules\cap\build\Release\cap.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\nodep\node_modules\cap\lib\Cap.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by RoshDevi** [comment]
Hello,


module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: %1 is not a valid Win32 application.
D:\nodep\node_modules\cap\build\Release\cap.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\nodep\node_modules\cap\lib\Cap.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I am facing the same issue. I have installed node 64 bit version in windows 7 64-bit. When I tried to run the test case which has cap module, it is throwing the above error. 
I need your support is resolving this error. Any log file you want, I can send that.
