### ISSUE TITLE
Common Issue: DLL Loading

### ISSUE THREAD

**Issue by vozitox** [mscdex/cap#70]
Hi! I am on Windows 10 Pro and I am trying to get the demo code up and running, but I run into the following error:

internal/modules/cjs/loader.js:731
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\Geometric Algorithm\Desktop\GeometricSniffer\node_modules\cap\build\Release\cap.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Geometric Algorithm\Desktop\GeometricSniffer\node_modules\cap\lib\Cap.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)

These two tickets seem two have the exact same issue, with no resolution:

https://github.com/mscdex/cap/issues/48
https://github.com/mscdex/cap/issues/63

My node version: 10.5.0
My python version: 2.7.3

Thank you in advance!

**Comment by mscdex** [comment]
Do you have npcap installed (with winpcap compatibility mode) as noted in the readme?

**Comment by vozitox** [comment]
Mad <3 and respect for the swift reply!

Issue resolved.
